  
# This is a basic workflow to help you get started with Actions

name: TRIPS-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ POI(ASP.Net) ]
    paths: 'apis/trips/**'
  pull_request:
    branches: [ master ]
    paths: 'apis/trips/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel      
jobs:
  # Name of the job that will run 
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
      - name: Checkout code
        uses: actions/checkout@v2
      #Install Go  
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      #Build image
      - name: Build
        run: go build -v
        working-directory: apis/trips
      #Unit testing go for api trips 
      - name: Test
        run: go test ./tests
        working-directory: apis/trips
